project_id = "etqwuohosdcxipvwevxt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://etqwuohosdcxipvwevxt.supabase.co"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[functions.chatbot]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = true

[functions.notify-ticket-created]
verify_jwt = true

[functions.notify-ticket-status-change]
verify_jwt = true

[functions.daily-ticket-summary]
verify_jwt = false

[functions.suggest-kb-articles]
verify_jwt = false
