// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etqwuohosdcxipvwevxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cXd1b2hvc2RjeGlwdndldnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTM4MTAsImV4cCI6MjA3Mzc4OTgxMH0.GJZEFkh4g3ISAJp-1x73Ihnusl896IKKb5wY4LLO7K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});